# Generated by Django 4.0.2 on 2022-02-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('immoweb_code', models.IntegerField(primary_key=True, serialize=False)),
                ('has_agency', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
            },
        ),
    ]
