# Generated by Django 4.0.2 on 2022-02-11 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('has_agency', models.BooleanField(default=False)),
                ('delay', models.SmallIntegerField(default=0)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'prospection rule',
                'verbose_name_plural': 'prospection rules',
            },
        ),
        migrations.CreateModel(
            name='ProspectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospection.prospectionrule')),
            ],
            options={
                'verbose_name': 'prospection log',
                'verbose_name_plural': 'prospection logs',
            },
        ),
    ]
